services:
    app:
        build: .
        ports:
            - "3000:3000"
        env_file:
            - .env.production
        restart: unless-stopped
        healthcheck:
            test:
                [
                    "CMD",
                    "wget",
                    "--spider",
                    "http://localhost:3000/.well-known/jwks.json",
                ]
            interval: 30s
            timeout: 10s
            retries: 3
